language: node_js

node_js:
  - 9

cache:
  directories:
  - node_modules

script:
  - npm run build

after_success:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github-tokenCookies: $GITHUB_tokenCookies
  keep-history: true
  email: simsim0709@gmail.com
  name: Ilkwon Sim
  local-dir: build
  on:
    branch: master
